from collections import Counter
from dataclasses import asdict
from pathlib import Path
import zipfile

from constants import (
    APP_NAME,
    APP_VERSION,
    AUTHOR,
    REPOSITORY_NAME,
    REPOSITORY_URL,
)
from models import (
    ScanResult,
    ScanSettings,
)
from scanner import build_tree
from utils import (
    language_hint,
    safe_read,
)


def build_manifest(
    root: Path,
    scan: ScanResult,
    settings: ScanSettings,
    created: str,
) -> dict:
    """
    Build PROJECT_MANIFEST.json.
    """
    return {
        "created": created,
        "app_name": APP_NAME,
        "version": APP_VERSION,
        "author": AUTHOR,
        "repository_name": REPOSITORY_NAME,
        "repository_url": REPOSITORY_URL,
        "root": str(root),
        "settings": settings.to_jsonable(),
        "summary": {
            "included_count": len(scan.included_records),
            "skipped_count": len(scan.skipped_records),
            "included_bytes": scan.total_included_bytes,
        },
        "included_files": [
            asdict(record)
            for record in scan.included_records
        ],
        "skipped_files": [
            asdict(record)
            for record in scan.skipped_records
        ],
    }


def build_context_markdown(
    root: Path,
    scan: ScanResult,
    settings: ScanSettings,
    created: str,
) -> str:
    """
    Build PROJECT_CONTEXT.md.
    """
    chunks: list[str] = []

    skip_counts = Counter(
        record.reason
        for record in scan.skipped_records
    )

    chunks.append("# Project Context")
    chunks.append("")
    chunks.append(f"Generated by **{APP_NAME} v{APP_VERSION}**")
    chunks.append(f"Created: `{created}`")
    chunks.append(f"Author: **{AUTHOR}**")
    chunks.append(f"Repository: {REPOSITORY_URL}")
    chunks.append(f"Root: `{root}`")
    chunks.append(f"Profile: `{settings.profile}`")
    chunks.append(f"Redaction enabled: `{settings.redact_sensitive_lines}`")
    chunks.append("")

    chunks.append("## Export Summary")
    chunks.append("")
    chunks.append(f"- Included files: **{len(scan.included_records)}**")
    chunks.append(f"- Skipped files: **{len(scan.skipped_records)}**")
    chunks.append(f"- Included bytes: **{scan.total_included_bytes}**")
    chunks.append(f"- Max file bytes: **{settings.max_file_bytes}**")
    chunks.append(f"- Max total bytes: **{settings.max_total_bytes}**")
    chunks.append(f"- Snapshot ZIP enabled: **{settings.include_snapshot_zip}**")
    chunks.append(f"- Hashes enabled: **{settings.include_hashes}**")
    chunks.append(f"- Line counts enabled: **{settings.include_line_counts}**")
    chunks.append("")

    if skip_counts:
        chunks.append("## Skip Reason Summary")
        chunks.append("")

        for reason, count in sorted(skip_counts.items()):
            chunks.append(f"- `{reason}`: {count}")

        chunks.append("")

    if settings.include_skipped_details and scan.skipped_records:
        chunks.append("## Skipped File Details")
        chunks.append("")

        limit = max(
            0,
            settings.skipped_details_limit,
        )

        visible_records = scan.skipped_records[:limit]

        chunks.append("| File | Reason | Bytes |")
        chunks.append("|---|---|---:|")

        for record in visible_records:
            size_display = (
                ""
                if record.size_bytes is None
                else str(record.size_bytes)
            )

            chunks.append(
                f"| `{record.relative_path}` "
                f"| `{record.reason}` "
                f"| {size_display} |"
            )

        remaining = len(scan.skipped_records) - len(visible_records)

        if remaining > 0:
            chunks.append("")
            chunks.append(
                f"_Skipped details truncated. "
                f"{remaining} additional skipped files are listed in PROJECT_MANIFEST.json._"
            )

        chunks.append("")

    if settings.include_folder_tree:
        chunks.append("## Folder Tree")
        chunks.append("")
        chunks.append("```text")
        chunks.append(
            build_tree(
                root,
                settings,
            )
        )
        chunks.append("```")
        chunks.append("")

    if settings.include_file_index:
        chunks.append("## File Index")
        chunks.append("")

        if scan.included_records:
            if settings.include_hashes:
                chunks.append("| File | Bytes | Lines | SHA256 |")
                chunks.append("|---|---:|---:|---|")
            else:
                chunks.append("| File | Bytes | Lines |")
                chunks.append("|---|---:|---:|")

            for record in scan.included_records:
                lines = (
                    ""
                    if record.line_count is None
                    else str(record.line_count)
                )

                if settings.include_hashes:
                    sha = record.sha256 or ""

                    chunks.append(
                        f"| `{record.relative_path}` "
                        f"| {record.size_bytes} "
                        f"| {lines} "
                        f"| `{sha}` |"
                    )
                else:
                    chunks.append(
                        f"| `{record.relative_path}` "
                        f"| {record.size_bytes} "
                        f"| {lines} |"
                    )

            chunks.append("")
        else:
            chunks.append("_No files were included._")
            chunks.append("")

    if settings.include_file_contents:
        chunks.append("## Included File Contents")
        chunks.append("")

        for path in scan.included_paths:
            rel = path.relative_to(root)

            chunks.append(f"### `{rel}`")
            chunks.append("")
            chunks.append(f"```{language_hint(path)}")
            chunks.append(
                safe_read(
                    path,
                    redact_sensitive_lines=settings.redact_sensitive_lines,
                )
            )
            chunks.append("```")
            chunks.append("")

    return "\n".join(chunks)


def build_summary_text(
    root: Path,
    scan: ScanResult,
    settings: ScanSettings,
    created: str,
) -> str:
    """
    Build PROJECT_SUMMARY.txt.
    """
    extension_counts = Counter(
        record.extension
        for record in scan.included_records
    )

    skip_counts = Counter(
        record.reason
        for record in scan.skipped_records
    )

    lines: list[str] = []

    lines.append(f"{APP_NAME} v{APP_VERSION}")
    lines.append(f"Created: {created}")
    lines.append(f"Author: {AUTHOR}")
    lines.append(f"Repository: {REPOSITORY_URL}")
    lines.append(f"Root: {root}")
    lines.append(f"Profile: {settings.profile}")
    lines.append("")

    lines.append("Settings")
    lines.append("--------")
    lines.append(f"Snapshot ZIP: {settings.include_snapshot_zip}")
    lines.append(f"Redaction: {settings.redact_sensitive_lines}")
    lines.append(f"Hashes: {settings.include_hashes}")
    lines.append(f"Line counts: {settings.include_line_counts}")
    lines.append(f"Folder tree: {settings.include_folder_tree}")
    lines.append(f"File index: {settings.include_file_index}")
    lines.append(f"File contents: {settings.include_file_contents}")
    lines.append("")

    lines.append("Summary")
    lines.append("-------")
    lines.append(f"Included files: {len(scan.included_records)}")
    lines.append(f"Skipped files: {len(scan.skipped_records)}")
    lines.append(f"Included bytes: {scan.total_included_bytes}")
    lines.append("")

    lines.append("Extensions")
    lines.append("----------")

    for ext, count in sorted(extension_counts.items()):
        lines.append(f"{ext}: {count}")

    lines.append("")

    lines.append("Skip Reasons")
    lines.append("------------")

    for reason, count in sorted(skip_counts.items()):
        lines.append(f"{reason}: {count}")

    return "\n".join(lines)


def create_snapshot_zip(
    zip_path: Path,
    context_path: Path,
    manifest_path: Path,
    summary_path: Path,
    settings_path: Path,
    scan: ScanResult,
    root: Path,
) -> None:
    """
    Build PROJECT_SNAPSHOT.zip.

    The ZIP includes:
    - generated export files
    - included project source files under project_files/
    """
    with zipfile.ZipFile(
        zip_path,
        "w",
        zipfile.ZIP_DEFLATED,
    ) as archive:
        archive.write(
            context_path,
            context_path.name,
        )

        archive.write(
            manifest_path,
            manifest_path.name,
        )

        archive.write(
            summary_path,
            summary_path.name,
        )

        archive.write(
            settings_path,
            settings_path.name,
        )

        for path in scan.included_paths:
            rel = path.relative_to(root)

            archive.write(
                path,
                f"project_files/{rel.as_posix()}",
            )